name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4

    # Used to host cibuildwheel
    - uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install bump2version

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.18.0

    - name: Build wheels
      run: python -m cibuildwheel --output-dir dist
      # to supply options, put them in 'env', like:
      # env:
      #   CIBW_SOME_OPTION: value

    # conditional. do only if publish
    - name: Publish wheels
      if: github.event_name == 'published'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    # bump version after publish
    - name: Bump version
      if: github.event_name == 'published'
      run: bump2version patch
